#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := lora-test

EXTRA_COMPONENT_DIRS := $(abspath ../..)

include $(IDF_PATH)/make/project.mk

